# -*- coding: utf-8 -*-
"""exp1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yPoInfI7Z7qkaZD06B9H3ylJJDqhZnUP
"""

#hardcoded variables
a = 10
b = 20
result = a + b
print(f"hardcoded addition:{a} + {b} = {result}")

#keyboard input
try:
  x = int(input("enter the firt number: "))
  y = int(input("enter the second number: "))
  result = x + y
  print(f"user input addition: {x} + {y} = {result}")
except ValueError:
  print("please enter valid integers!")

with open("single_input.txt","w") as f:
  f.write("42")
try:
  with open("single_input.txt","r") as f:
    num = int(f.read().strip())
    result = num*2
    print(f"single  input read from file: {num} * 2 = {result}")
except FileNotFoundError:
  print("file not found")
except ValueError:
  print("error in reading or converting the input")

with open("multiple_inputs.txt","w") as f:
  f.write("3\n5\n7")
try:
  with open("multiple_inputs.txt","r") as f:
    numbers = [int(line.strip()) for line in f.readlines()]
    result = sum(numbers)
    print(f"multiple inputs read from file: {numbers},sum = {result}")
except FileNotFoundError:
  print("file not found")
except ValueError:
  print("error in reading or converting the input")